### ISSUE TITLE
AWS Premium Support Subscription is required to use this service. (Aws::Support::Errors::SubscriptionRequiredException)

### ISSUE THREAD

**Issue by rams3sh** [joshlarsen/aws-recon#1]
Run log below :-
```
~/aws-recon #  AWS_PROFILE=default ruby recon.rb -v
Starting collection...
t3.global.Shield.ResourceNotFoundException
t2.global.S3.list_buckets.0
t2.global.S3.list_buckets.config-bucket-<redacted>
t0.global.EC2.describe_account_attributes
t2.global.S3.list_buckets.<redacted>
t2.global.S3.list_buckets.<redacted>
t1.global.IAM.get_account_authorization_details.0
t1.global.IAM.get_account_authorization_details.1
t1.global.IAM.get_account_password_policy
t1.global.IAM.get_account_summary
t1.global.IAM.list_server_certificates.0
t1.global.IAM.list_virtual_mfa_devices.0

Finished in 17 seconds. Saving resources to output.json.

Traceback (most recent call last):
	15: from /usr/local/bundle/gems/parallel-1.19.2/lib/parallel.rb:211:in `block (4 levels) in in_threads'
	14: from /usr/local/bundle/gems/parallel-1.19.2/lib/parallel.rb:360:in `block in work_in_threads'
	13: from /usr/local/bundle/gems/parallel-1.19.2/lib/parallel.rb:519:in `with_instrumentation'
	12: from /usr/local/bundle/gems/parallel-1.19.2/lib/parallel.rb:361:in `block (2 levels) in work_in_threads'
	11: from /usr/local/bundle/gems/parallel-1.19.2/lib/parallel.rb:508:in `call_with_index'
	10: from recon.rb:72:in `block in <main>'
	 9: from recon.rb:42:in `collect'
	 8: from /root/aws-recon/collectors/support.rb:11:in `collect'
	 7: from /usr/local/bundle/gems/aws-sdk-support-1.25.0/lib/aws-sdk-support/client.rb:1219:in `describe_trusted_advisor_checks'
	 6: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/seahorse/client/request.rb:72:in `send_request'
	 5: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
	 4: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
	 3: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
	 2: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
	 1: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': AWS Premium Support Subscription is required to use this service. (Aws::Support::Errors::SubscriptionRequiredException)
```

These are my environment details :- 

## Running it in Docker Image : ruby:2.6-alpine

Dockerfile below :- 
```
FROM ruby2.6:alpine
WORKDIR /aws-recon/
apk update && apk --no-cache --update add git build-base
bundler install
```
I have cloned the repo and mounted  the folder within /aws-recon/ path inside the container.

## Docker Container OS details: 
```
~/aws-recon #  uname -a
Linux 51c29d7be40c 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 Linux
```

## Local Ruby Gems installed :-
```
~/aws-recon # gem query --local

*** LOCAL GEMS ***

ast (2.4.1)
aws-eventstream (1.1.0)
aws-partitions (1.339.0)
aws-sdk (3.0.1)
aws-sdk-accessanalyzer (1.9.0)
aws-sdk-acm (1.34.0)
aws-sdk-acmpca (1.26.0)
aws-sdk-alexaforbusiness (1.39.0)
aws-sdk-amplify (1.20.0)
aws-sdk-apigateway (1.48.0)
aws-sdk-apigatewaymanagementapi (1.16.0)
aws-sdk-apigatewayv2 (1.23.0)
aws-sdk-appconfig (1.9.0)
aws-sdk-applicationautoscaling (1.43.0)
aws-sdk-applicationdiscoveryservice (1.30.0)
aws-sdk-applicationinsights (1.12.0)
aws-sdk-appmesh (1.27.0)
aws-sdk-appstream (1.44.0)
aws-sdk-appsync (1.29.0)
aws-sdk-athena (1.30.0)
aws-sdk-augmentedairuntime (1.7.0)
aws-sdk-autoscaling (1.43.0)
aws-sdk-autoscalingplans (1.25.0)
aws-sdk-backup (1.18.0)
aws-sdk-batch (1.34.0)
aws-sdk-budgets (1.32.0)
aws-sdk-chime (1.32.0)
aws-sdk-cloud9 (1.25.0)
aws-sdk-clouddirectory (1.26.0)
aws-sdk-cloudformation (1.41.0)
aws-sdk-cloudfront (1.34.0)
aws-sdk-cloudhsm (1.24.0)
aws-sdk-cloudhsmv2 (1.26.0)
aws-sdk-cloudsearch (1.23.0)
aws-sdk-cloudsearchdomain (1.19.0)
aws-sdk-cloudtrail (1.26.0)
aws-sdk-cloudwatch (1.41.0)
aws-sdk-cloudwatchevents (1.32.0)
aws-sdk-cloudwatchlogs (1.34.0)
aws-sdk-codeartifact (1.1.0)
aws-sdk-codebuild (1.56.0)
aws-sdk-codecommit (1.37.0)
aws-sdk-codedeploy (1.34.0)
aws-sdk-codeguruprofiler (1.8.0)
aws-sdk-codegurureviewer (1.9.0)
aws-sdk-codepipeline (1.34.0)
aws-sdk-codestar (1.24.0)
aws-sdk-codestarconnections (1.7.0)
aws-sdk-codestarnotifications (1.5.0)
aws-sdk-cognitoidentity (1.24.0)
aws-sdk-cognitoidentityprovider (1.42.0)
aws-sdk-cognitosync (1.21.0)
aws-sdk-comprehend (1.34.0)
aws-sdk-comprehendmedical (1.20.0)
aws-sdk-computeoptimizer (1.5.0)
aws-sdk-configservice (1.48.0)
aws-sdk-connect (1.28.0)
aws-sdk-connectparticipant (1.5.0)
aws-sdk-core (3.103.0)
aws-sdk-costandusagereportservice (1.24.0)
aws-sdk-costexplorer (1.44.0)
aws-sdk-databasemigrationservice (1.38.0)
aws-sdk-dataexchange (1.7.0)
aws-sdk-datapipeline (1.21.0)
aws-sdk-datasync (1.22.0)
aws-sdk-dax (1.24.0)
aws-sdk-detective (1.8.0)
aws-sdk-devicefarm (1.36.0)
aws-sdk-directconnect (1.33.0)
aws-sdk-directoryservice (1.31.0)
aws-sdk-dlm (1.31.0)
aws-sdk-docdb (1.20.0)
aws-sdk-dynamodb (1.51.0)
aws-sdk-dynamodbstreams (1.21.0)
aws-sdk-ebs (1.6.0)
aws-sdk-ec2 (1.175.0)
aws-sdk-ec2instanceconnect (1.8.0)
aws-sdk-ecr (1.34.0)
aws-sdk-ecs (1.67.0)
aws-sdk-efs (1.33.0)
aws-sdk-eks (1.39.0)
aws-sdk-elasticache (1.40.0)
aws-sdk-elasticbeanstalk (1.34.0)
aws-sdk-elasticinference (1.7.0)
aws-sdk-elasticloadbalancing (1.25.0)
aws-sdk-elasticloadbalancingv2 (1.47.0)
aws-sdk-elasticsearchservice (1.39.0)
aws-sdk-elastictranscoder (1.24.0)
aws-sdk-emr (1.34.0)
aws-sdk-eventbridge (1.10.0)
aws-sdk-firehose (1.31.0)
aws-sdk-fms (1.28.0)
aws-sdk-forecastqueryservice (1.7.0)
aws-sdk-forecastservice (1.7.0)
aws-sdk-frauddetector (1.6.0)
aws-sdk-fsx (1.23.0)
aws-sdk-gamelift (1.34.0)
aws-sdk-glacier (1.32.0)
aws-sdk-globalaccelerator (1.20.0)
aws-sdk-glue (1.63.0)
aws-sdk-greengrass (1.33.0)
aws-sdk-groundstation (1.10.0)
aws-sdk-guardduty (1.36.0)
aws-sdk-health (1.27.0)
aws-sdk-honeycode (1.0.0)
aws-sdk-iam (1.43.0)
aws-sdk-imagebuilder (1.11.0)
aws-sdk-importexport (1.21.0)
aws-sdk-inspector (1.29.0)
aws-sdk-iot (1.54.0)
aws-sdk-iot1clickdevicesservice (1.23.0)
aws-sdk-iot1clickprojects (1.23.0)
aws-sdk-iotanalytics (1.31.0)
aws-sdk-iotdataplane (1.23.0)
aws-sdk-iotevents (1.17.0)
aws-sdk-ioteventsdata (1.10.0)
aws-sdk-iotjobsdataplane (1.22.0)
aws-sdk-iotsecuretunneling (1.5.0)
aws-sdk-iotsitewise (1.7.0)
aws-sdk-iotthingsgraph (1.9.0)
aws-sdk-kafka (1.23.0)
aws-sdk-kendra (1.8.0)
aws-sdk-kinesis (1.26.0)
aws-sdk-kinesisanalytics (1.26.0)
aws-sdk-kinesisanalyticsv2 (1.18.0)
aws-sdk-kinesisvideo (1.27.0)
aws-sdk-kinesisvideoarchivedmedia (1.26.0)
aws-sdk-kinesisvideomedia (1.23.0)
aws-sdk-kinesisvideosignalingchannels (1.5.0)
aws-sdk-kms (1.36.0)
aws-sdk-lakeformation (1.7.0)
aws-sdk-lambda (1.46.0)
aws-sdk-lambdapreview (1.21.0)
aws-sdk-lex (1.28.0)
aws-sdk-lexmodelbuildingservice (1.33.0)
aws-sdk-licensemanager (1.16.0)
aws-sdk-lightsail (1.35.0)
aws-sdk-machinelearning (1.22.0)
aws-sdk-macie (1.22.0)
aws-sdk-macie2 (1.5.0)
aws-sdk-managedblockchain (1.13.0)
aws-sdk-marketplacecatalog (1.5.0)
aws-sdk-marketplacecommerceanalytics (1.26.0)
aws-sdk-marketplaceentitlementservice (1.21.0)
aws-sdk-marketplacemetering (1.28.0)
aws-sdk-mediaconnect (1.24.0)
aws-sdk-mediaconvert (1.53.0)
aws-sdk-medialive (1.49.0)
aws-sdk-mediapackage (1.30.0)
aws-sdk-mediapackagevod (1.16.0)
aws-sdk-mediastore (1.27.0)
aws-sdk-mediastoredata (1.24.0)
aws-sdk-mediatailor (1.29.0)
aws-sdk-migrationhub (1.26.0)
aws-sdk-migrationhubconfig (1.6.0)
aws-sdk-mobile (1.21.0)
aws-sdk-mq (1.29.0)
aws-sdk-mturk (1.24.0)
aws-sdk-neptune (1.27.0)
aws-sdk-networkmanager (1.5.0)
aws-sdk-opsworks (1.27.0)
aws-sdk-opsworkscm (1.37.0)
aws-sdk-organizations (1.44.0)
aws-sdk-outposts (1.7.0)
aws-sdk-personalize (1.15.0)
aws-sdk-personalizeevents (1.9.0)
aws-sdk-personalizeruntime (1.13.0)
aws-sdk-pi (1.21.0)
aws-sdk-pinpoint (1.43.0)
aws-sdk-pinpointemail (1.21.0)
aws-sdk-pinpointsmsvoice (1.18.0)
aws-sdk-polly (1.34.0)
aws-sdk-pricing (1.21.0)
aws-sdk-qldb (1.8.0)
aws-sdk-qldbsession (1.6.0)
aws-sdk-quicksight (1.25.0)
aws-sdk-ram (1.19.0)
aws-sdk-rds (1.93.0)
aws-sdk-rdsdataservice (1.20.0)
aws-sdk-redshift (1.46.0)
aws-sdk-rekognition (1.42.0)
aws-sdk-resourcegroups (1.26.0)
aws-sdk-resourcegroupstaggingapi (1.28.0)
aws-sdk-resources (3.75.0)
aws-sdk-robomaker (1.26.0)
aws-sdk-route53 (1.40.0)
aws-sdk-route53domains (1.25.0)
aws-sdk-route53resolver (1.17.0)
aws-sdk-s3 (1.73.0)
aws-sdk-s3control (1.21.0)
aws-sdk-sagemaker (1.62.0)
aws-sdk-sagemakerruntime (1.24.0)
aws-sdk-savingsplans (1.7.0)
aws-sdk-schemas (1.6.0)
aws-sdk-secretsmanager (1.39.0)
aws-sdk-securityhub (1.29.0)
aws-sdk-serverlessapplicationrepository (1.29.0)
aws-sdk-servicecatalog (1.43.0)
aws-sdk-servicediscovery (1.26.0)
aws-sdk-servicequotas (1.8.0)
aws-sdk-ses (1.33.0)
aws-sdk-sesv2 (1.8.0)
aws-sdk-shield (1.29.0)
aws-sdk-signer (1.23.0)
aws-sdk-simpledb (1.21.0)
aws-sdk-sms (1.23.0)
aws-sdk-snowball (1.31.0)
aws-sdk-sns (1.27.0)
aws-sdk-sqs (1.30.0)
aws-sdk-ssm (1.84.0)
aws-sdk-sso (1.6.0)
aws-sdk-ssooidc (1.5.0)
aws-sdk-states (1.31.0)
aws-sdk-storagegateway (1.45.0)
aws-sdk-support (1.25.0)
aws-sdk-swf (1.22.0)
aws-sdk-synthetics (1.5.0)
aws-sdk-textract (1.17.0)
aws-sdk-transcribeservice (1.45.0)
aws-sdk-transcribestreamingservice (1.17.0)
aws-sdk-transfer (1.23.0)
aws-sdk-translate (1.24.0)
aws-sdk-waf (1.33.0)
aws-sdk-wafregional (1.34.0)
aws-sdk-wafv2 (1.8.0)
aws-sdk-workdocs (1.25.0)
aws-sdk-worklink (1.18.0)
aws-sdk-workmail (1.27.0)
aws-sdk-workmailmessageflow (1.6.0)
aws-sdk-workspaces (1.40.0)
aws-sdk-xray (1.28.0)
aws-sigv2 (1.0.1)
aws-sigv4 (1.2.1)
backport (1.1.2)
benchmark (0.1.0)
bigdecimal (default: 1.4.1)
bundler (default: 1.17.2)
cmath (default: 1.0.0)
coderay (1.1.3)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.0)
e2mmap (default: 0.1.0)
etc (default: 1.0.1)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
gdbm (default: 2.0.0)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
jaro_winkler (1.5.4)
jmespath (1.4.0)
json (default: 2.1.0)
logger (default: 1.3.0)
maruku (0.7.3)
matrix (default: 0.1.0)
method_source (1.0.0)
mini_portile2 (2.4.0)
minitest (5.11.3)
mutex_m (default: 0.1.0)
net-telnet (0.2.0)
nokogiri (1.10.10)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
parallel (1.19.2)
parser (2.7.1.4)
power_assert (1.1.3)
prime (default: 0.1.0)
pry (0.13.1)
psych (default: 3.1.0)
rainbow (3.0.0)
rake (12.3.3)
rdoc (default: 6.1.2)
regexp_parser (1.7.1)
reverse_markdown (2.0.0)
rexml (3.2.4, default: 3.1.9)
rss (default: 0.2.7)
rubocop (0.87.1)
rubocop-ast (0.1.0)
ruby-progressbar (1.10.1)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (default: 0.7)
solargraph (0.39.11)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
test-unit (3.2.9)
thor (1.0.1)
thwait (default: 0.1.0)
tilt (2.0.10)
tracer (default: 0.1.0)
unicode-display_width (1.7.0)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
yard (0.9.25)
zlib (default: 1.0.0)

```
Let me know if you need any more details

**Comment by joshlarsen** [comment]
Ah yes, good catch.
