### ISSUE TITLE
InvalidSignatureException for profiles with default resgion not set to us-east

### ISSUE THREAD

**Issue by marco-lancini** [joshlarsen/aws-recon#13]
Hello,
I've found the following error to occur if the default region of the AWS profile used is not set to `us-east-1` (I've tried with `eu-west-2` and `us-west-1`):

```bash
root@docker:/app# AWS_PROFILE=test ./recon.rb -v

Starting collection with 8 threads...

Finished in 0 seconds. Saving resources to output.json.

Traceback (most recent call last):
	12: from ./recon.rb:67:in `<main>'
	11: from ./recon.rb:67:in `each'
	10: from ./recon.rb:74:in `block in <main>'
	 9: from ./recon.rb:44:in `collect'
	 8: from /app/collectors/organizations.rb:11:in `collect'
	 7: from /usr/local/bundle/gems/aws-sdk-organizations-1.44.0/lib/aws-sdk-organizations/client.rb:2036:in `describe_organization'
	 6: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/seahorse/client/request.rb:72:in `send_request'
	 5: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
	 4: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
	 3: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
	 2: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
	 1: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': Credential should be scoped to a valid region, not 'eu-west-2'.  (Aws::Organizations::Errors::InvalidSignatureException)
```

AWS profile:

```bash
[profile test]
output = json
region = eu-west-2
```

**Comment by joshlarsen** [comment]
@marco-lancini good catch, thanks. Organizations only uses the `us-east-1` [endpoint](https://docs.aws.amazon.com/general/latest/gr/ao.html) for non Gov/CN regions. I have updated the client instance used for Organizations.

**Comment by marco-lancini** [comment]
Sure, but if an user of `aws-recon` has a profile defaulting to another region (set in `~/.aws/config`), then it will crash on startup.

**Comment by joshlarsen** [comment]
I'm not sure I understand what you are saying. The client created by `aws-recon` will now override the region and use `us-east-1` for Organizations.
