### ISSUE TITLE
CloudTrailARNInvalidException while ingesting CloudTrail

### ISSUE THREAD

**Issue by marco-lancini** [joshlarsen/aws-recon#14]
Hi, I'm getting the following `CloudTrailARNInvalidException` while ingesting CloudTrail:

```bash
root@docker:/app# AWS_PROFILE=test ./recon.rb -v

Starting collection with 8 threads...
t0.global.Organizations.describe_organization
t0.global.Organizations.list_handshakes_for_account.0
t0.global.EC2.describe_account_attributes
t0.global.IAM.get_account_authorization_details.0
t0.global.IAM.get_account_password_policy
t0.global.IAM.get_account_summary
t0.global.IAM.list_server_certificates.0
t0.global.IAM.list_virtual_mfa_devices.0
t0.global.IAM.ReportNotPresent
t0.global.S3.list_buckets.0
t0.global.S3.list_buckets.cloudseclist-test
t1.global.S3.list_buckets.csl-test-sest2.global.S3.list_buckets.ml-central-logging
t0.global.Route53Domains.list_domains.0
t0.global.Shield.ResourceNotFoundException
t0.global.Support.SubscriptionRequiredException
t6.eu-north-1.EC2.describe_instances.0
t5.eu-north-1.CloudTrail.describe_trails.0
t6.eu-north-1.EC2.describe_vpcs.0
t0.eu-north-1.CodeBuild.list_projects.0
t7.eu-north-1.EKS.list_clusters.0
t2.eu-north-1.CodePipeline.list_pipelines.0
t6.eu-north-1.EC2.describe_security_groups.0
t1.eu-north-1.ConfigService.describe_config_rules.0
t6.eu-north-1.EC2.describe_network_interfaces.0
t1.eu-north-1.ConfigService.describe_configuration_recorders.0
t1.eu-north-1.ConfigService.describe_delivery_channels.0
t6.eu-north-1.EC2.describe_subnets.0
t4.eu-north-1.AutoScaling.describe_auto_scaling_groups.0
t7.eu-north-1.ElasticLoadBalancing.describe_load_balancers.0
t0.eu-north-1.ECS.describe_clusters.0
t6.eu-north-1.EC2.describe_addresses.0
t6.eu-north-1.EC2.describe_nat_gateways.0
t6.eu-north-1.EC2.describe_route_tables.0
t3.eu-north-1.CloudFront.list_distributions.0
t6.eu-north-1.EC2.describe_images.0
t6.eu-north-1.EC2.describe_snapshots.0
t6.eu-north-1.EC2.describe_flow_logs.0
t6.eu-north-1.EC2.describe_volumes.0
t6.eu-north-1.EC2.describe_vpn_gateways.0
t6.eu-north-1.EC2.describe_vpc_peering_connections.0

Finished in 13 seconds. Saving resources to output.json.

Traceback (most recent call last):
	20: from /usr/local/bundle/gems/parallel-1.19.2/lib/parallel.rb:211:in `block (4 levels) in in_threads'
	19: from /usr/local/bundle/gems/parallel-1.19.2/lib/parallel.rb:360:in `block in work_in_threads'
	18: from /usr/local/bundle/gems/parallel-1.19.2/lib/parallel.rb:519:in `with_instrumentation'
	17: from /usr/local/bundle/gems/parallel-1.19.2/lib/parallel.rb:361:in `block (2 levels) in work_in_threads'
	16: from /usr/local/bundle/gems/parallel-1.19.2/lib/parallel.rb:508:in `call_with_index'
	15: from ./recon.rb:91:in `block (2 levels) in <main>'
	14: from ./recon.rb:44:in `collect'
	13: from /app/collectors/cloudtrail.rb:10:in `collect'
	12: from /app/collectors/cloudtrail.rb:10:in `each_with_index'
	11: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/pageable_response.rb:91:in `each'
	10: from /app/collectors/cloudtrail.rb:13:in `block in collect'
	 9: from /app/collectors/cloudtrail.rb:13:in `each'
	 8: from /app/collectors/cloudtrail.rb:22:in `block (2 levels) in collect'
	 7: from /usr/local/bundle/gems/aws-sdk-cloudtrail-1.26.0/lib/aws-sdk-cloudtrail/client.rb:978:in `list_tags'
	 6: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/seahorse/client/request.rb:72:in `send_request'
	 5: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
	 4: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
	 3: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
	 2: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
	 1: from /usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.103.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': AccountID in ARN is wrong, you can only access resources with AccountID <REDACTED>. (Aws::CloudTrail::Errors::CloudTrailARNInvalidException)
```

**Comment by joshlarsen** [comment]
Hi @marco-lancini, I have not seen this specific error before. Can you share any other information about the trail and/or the account?
