### ISSUE TITLE
CloudTrail client using wrong region

### ISSUE THREAD

**Issue by joshlarsen** [joshlarsen/aws-recon#5]
CloudTrail calls fail if a prior trail required changing `home_region`.

```
Traceback (most recent call last):
	23: from ./recon.rb:80:in `<main>'
	22: from ./recon.rb:80:in `each'
	21: from ./recon.rb:81:in `block in <main>'
	20: from /.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/parallel-1.19.2/lib/parallel.rb:274:in `map'
	19: from /.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/parallel-1.19.2/lib/parallel.rb:336:in `work_direct'
	18: from /.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/parallel-1.19.2/lib/parallel.rb:519:in `with_instrumentation'
	17: from /.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/parallel-1.19.2/lib/parallel.rb:337:in `block in work_direct'
	16: from /.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/parallel-1.19.2/lib/parallel.rb:508:in `call_with_index'
	15: from ./recon.rb:91:in `block (2 levels) in <main>'
	14: from ./recon.rb:44:in `collect'
	13: from /code/tools/aws-recon/collectors/cloudtrail.rb:10:in `collect'
	12: from /code/tools/aws-recon/collectors/cloudtrail.rb:10:in `each_with_index'
	11: from /.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/pageable_response.rb:91:in `each'
	10: from /code/tools/aws-recon/collectors/cloudtrail.rb:13:in `block in collect'
	 9: from /code/tools/aws-recon/collectors/cloudtrail.rb:13:in `each'
	 8: from /code/tools/aws-recon/collectors/cloudtrail.rb:21:in `block (2 levels) in collect'
	 7: from /.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/aws-sdk-cloudtrail-1.26.0/lib/aws-sdk-cloudtrail/client.rb:978:in `list_tags'
	 6: from /.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/aws-sdk-core-3.103.0/lib/seahorse/client/request.rb:72:in `send_request'
	 5: from /.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/aws-sdk-core-3.103.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
	 4: from /.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
	 3: from /.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
	 2: from /.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
	 1: from /.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/aws-sdk-core-3.103.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
/.rvm/gems/ruby-2.6.5@aws-ruby-recon/gems/aws-sdk-core-3.103.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': Region in ARN is wrong, you can only access resources in region us-east-1. (Aws::CloudTrail::Errors::CloudTrailARNInvalidException)
```

**Comment by joshlarsen** [comment]
Set a new trail if needed

```ruby
Aws::CloudTrail::Client.new({ region: trail.home_region })
```
