### ISSUE TITLE
undefined method `downcase' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by maheshkukreja1** [joshlarsen/aws-recon#7]
Was testing the tool on my Mac, and I get the following error:

Profile: `default`

```
$ ./recon.rb -s ec2
Traceback (most recent call last):
	8: from ./recon.rb:5:in `<main>'
	7: from /Users/<redacted>/Downloads/Tools/aws-recon/config/options.rb:135:in `parse'
	6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/optparse.rb:1678:in `parse!'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/optparse.rb:1656:in `permute!'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/optparse.rb:1562:in `order!'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/optparse.rb:1568:in `parse_in_order'
	2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/optparse.rb:1568:in `catch'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/optparse.rb:1614:in `block in parse_in_order'
/Users/<redacted>/Downloads/Tools/aws-recon/config/options.rb:65:in `block (2 levels) in parse': undefined method `downcase' for nil:NilClass (NoMethodError)
```

Tried the following as well:

```
$ AWS_PROFILE=<some_profile_name> ./recon.rb -s ec2
Traceback (most recent call last):
	8: from ./recon.rb:5:in `<main>'
	7: from /Users/<redacted>/Downloads/Tools/aws-recon/config/options.rb:135:in `parse'
	6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/optparse.rb:1678:in `parse!'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/optparse.rb:1656:in `permute!'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/optparse.rb:1562:in `order!'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/optparse.rb:1568:in `parse_in_order'
	2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/optparse.rb:1568:in `catch'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/optparse.rb:1614:in `block in parse_in_order'
/Users/<redacted>/Downloads/Tools/aws-recon/config/options.rb:65:in `block (2 levels) in parse': undefined method `downcase' for nil:NilClass (NoMethodError)
```

My ruby version:

```
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
```

Any pointers for troubleshooting this?

**Comment by joshlarsen** [comment]
Try without a space between the `-s` and the `ec2`.

**Comment by maheshkukreja1** [comment]
Thanks, that worked
