### ISSUE TITLE
Crash on "no field 'Policy'" with SQS

### ISSUE THREAD

**Issue by ilkka** [joshlarsen/aws-recon#77]
Possibly related to #34 , just had this crash with the latest published image from Docker Hub:

```
Traceback (most recent call last):
	15: from /usr/local/bundle/gems/parallel-1.20.1/lib/parallel.rb:215:in `block (4 levels) in in_threads'
	14: from /usr/local/bundle/gems/parallel-1.20.1/lib/parallel.rb:366:in `block in work_in_threads'
	13: from /usr/local/bundle/gems/parallel-1.20.1/lib/parallel.rb:518:in `with_instrumentation'
	12: from /usr/local/bundle/gems/parallel-1.20.1/lib/parallel.rb:367:in `block (2 levels) in work_in_threads'
	11: from /usr/local/bundle/gems/parallel-1.20.1/lib/parallel.rb:507:in `call_with_index'
	10: from /usr/local/bundle/gems/aws_recon-0.2.25/lib/aws_recon/aws_recon.rb:99:in `block (2 levels) in start'
	 9: from /usr/local/bundle/gems/aws_recon-0.2.25/lib/aws_recon/aws_recon.rb:49:in `collect'
	 8: from /usr/local/bundle/gems/aws_recon-0.2.25/lib/aws_recon/collectors/sqs.rb:11:in `collect'
	 7: from /usr/local/bundle/gems/aws_recon-0.2.25/lib/aws_recon/collectors/sqs.rb:11:in `each_with_index'
	 6: from /usr/local/bundle/gems/aws-sdk-core-3.110.0/lib/aws-sdk-core/pageable_response.rb:93:in `each'
	 5: from /usr/local/bundle/gems/aws_recon-0.2.25/lib/aws_recon/collectors/sqs.rb:14:in `block in collect'
	 4: from /usr/local/bundle/gems/aws_recon-0.2.25/lib/aws_recon/collectors/sqs.rb:14:in `each'
	 3: from /usr/local/bundle/gems/aws_recon-0.2.25/lib/aws_recon/collectors/sqs.rb:21:in `block (2 levels) in collect'
	 2: from /usr/local/lib/ruby/2.6.0/ostruct.rb:314:in `delete_field'
	 1: from /usr/local/lib/ruby/2.6.0/ostruct.rb:314:in `delete'
/usr/local/lib/ruby/2.6.0/ostruct.rb:315:in `block in delete_field': no field `Policy' in #<OpenStruct QueueArn="arn:aws:sqs:eu-west-1:123456789:MyBestQueue", ApproximateNumberOfMessages="0", ApproximateNumberOfMessagesNotVisible="0", ApproximateNumberOfMessagesDelayed="0", CreatedTimestamp="1590487053", LastModifiedTimestamp="1593502746", VisibilityTimeout="70", MaximumMessageSize="262144", MessageRetentionPeriod="345600", DelaySeconds="5", ReceiveMessageWaitTimeSeconds="0", type="queue", arn="arn:aws:sqs:eu-west-1:123456789:MyBestQueue"> (NameError)
```

**Comment by joshlarsen** [comment]
Thanks for catching this. It will be fixed in the next version, later today.
